# NOTE: this is the production Docker Compose configuration file. DO NOT put
#       any stuff that must be available only in development. Please use the
#       file docker-compose.override.yml instead.
version: "2"
services:
  swarm-logger:
    image: bde2020/mu-swarm-logger-service
    links:
      - database:database
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  database:
    image: tenforce/virtuoso:1.1.1-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
  event-query:
    image: bde2020/mu-event-query-service
    links:
      - database:database
    volumes:
      - ./containers:/usr/src/app/containers/
    environment:
      SLEEP_PERIOD: '10'
  har-transformation:
    image: bde2020/mu-har-transformation-service
    volumes:
      - ./pcap:/app/pcap
      - ./har:/app/har
      - ./containers:/app/containers
      - ./backups:/app/backups
    links:
      - elasticsearch:elasticsearch
    environment:
      BU_DIR: "/app/backups"
  elasticsearch:
    image: elasticsearch:5.5.0
    # build: ../docker-elasticsearch
    command: elasticsearch -E network.host=0.0.0.0
    ports:
      - "9200:9200"
  kibana:
    image: kibana:5.5
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch:elasticsearch
